language: php

php:
  - 5.5
  - 5.6
  - 7
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: 7

before_script:
    - composer install --no-dev

script:
    - phpunit --coverage-clover=coverage.clover
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

sudo: false
