language: php

php:
  - 7.3
  - 7.4
  - 8.0

before_script:
    - composer install

script:
    - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

